// ticketLabels.ts
//
// Shared formatters for turning a backend Ticket row into the strings the
// UI shows the contractor.
//
// Why this file exists:
//   `ticket.service_type` is a foreign-key UUID into the `service` table on
//   the backend (values like CHEMICAL_DELIVERY, WATER_DELIVERY etc. live in
//   service.service). The /contractors/assigned-tickets endpoint currently
//   returns the raw UUID, which would render as "8044af1e-374b-..." if we
//   handed it to <Text> directly. Until the endpoint is extended to JOIN
//   service.service into the response, we keep an id->label map here so
//   both TicketsScreen and TicketDetailScreen render a real human name
//   without round-tripping the network.
//
// Update paths:
//   - If a new service category is added on the backend, append it to
//     SERVICE_NAME_BY_ID below.
//   - When the backend exposes the joined `service_name` field on the
//     ticket row, prefer that and treat this map as a fallback only.

/** Map of service.id -> service.service from the team Supabase project.
 *  Generated by inspecting the `service` table directly; values are the
 *  canonical enum stored on the backend. */
export const SERVICE_NAME_BY_ID: Record<string, string> = {
  'a199c9bb-b841-4422-80fd-42c7b7529770': 'CHEMICAL_DELIVERY',
  'f4147bc0-4335-4251-8b65-340945334870': 'EQUIPMENT_REPAIR',
  '7dc20248-73d1-4d1a-a5fd-9f9376b39470': 'INSPECTION',
  'd6b8e590-16bc-4d7f-8c5d-e9dd475b2cf3': 'PIPELINE_SERVICE',
  '8044af1e-374b-4af7-a61d-8a2bf183ae91': 'ROUTINE_MAINTENANCE',
  '3973f28b-f6d7-47c5-bcea-db559503f5ab': 'SITE_CLEANUP',
  '53abedb7-5e14-49e1-acbe-ec2638fdff0a': 'WATER_DELIVERY',
  'a47b1e88-2508-4773-a9ad-cf8ed4a21d22': 'WELL_INTERVENTION',
};

/** Turn UPPER_SNAKE_CASE into Title Case. "CHEMICAL_DELIVERY" -> "Chemical Delivery". */
export function titleCaseEnum(raw: string | null | undefined): string {
  if (!raw) return '';
  return raw
    .toLowerCase()
    .split(/[_\s]+/)
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/** Best-effort human label for a ticket.service_type value.
 *  - UUID matching SERVICE_NAME_BY_ID returns the formatted enum name
 *  - Already-human strings ("Chemical Delivery") pass through
 *  - Unknown UUID returns null so the caller can fall back further */
export function serviceLabel(serviceTypeRaw: string | null | undefined): string | null {
  if (!serviceTypeRaw) return null;
  const enumName = SERVICE_NAME_BY_ID[serviceTypeRaw];
  if (enumName) return titleCaseEnum(enumName);
  // Looks like a UUID but isn't in our map — don't show it.
  if (/^[0-9a-f-]{32,}$/i.test(serviceTypeRaw)) return null;
  // Some other shape — assume already a label and return as-is.
  return serviceTypeRaw;
}

/** Build the title shown on a ticket card / detail screen. Combines the
 *  service label with the first line of the description so cards stay
 *  readable when the contractor has multiple "INSPECTION" tickets at once.
 *  Falls back gracefully when fields are missing. */
export function ticketDisplayTitle(
  t: { service_type?: string | null; description?: string | null; id?: string | null },
): string {
  const label = serviceLabel(t.service_type);
  const desc  = (t.description || '').trim();
  const descShort = desc
    ? (desc.split(/\n|\.\s/)[0] || desc).slice(0, 50).trim()
    : '';

  if (label && descShort) {
    return `${label} — ${descShort}`;
  }
  if (label)     return label;
  if (descShort) return descShort.length > 60 ? `${descShort.slice(0, 60)}...` : descShort;
  if (t.id)      return `Ticket ${String(t.id).slice(0, 8)}`;
  return 'Ticket';
}
